name: iOS starter workflow

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test using available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Detect Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo "$scheme_list" | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "$default" > default_scheme.txt
          echo "Default scheme: $default"

      - name: Detect Available iOS Simulator
        id: find-simulator
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -E '^iPhone.*Simulator$' | head -n 1 | cut -d '(' -f1 | xargs)
          os=$(xcrun xctrace list devices 2>&1 | grep -E '^iPhone.*Simulator$' | head -n 1 | grep -oE '\([^)]+\)' | tr -d '()')
          echo "DEVICE_NAME=$device" >> $GITHUB_ENV
          echo "DEVICE_OS=$os" >> $GITHUB_ENV
          echo "🟢 Using simulator: $device ($os)"

      - name: Build for Testing
        run: |
          scheme=$(cat default_scheme.txt)
          if ls -A | grep -iq \.xcworkspace$; then
            filetype="workspace"
            file=$(ls -A | grep -i \.xcworkspace$)
          else
            filetype="project"
            file=$(ls -A | grep -i \.xcodeproj$)
          fi

          xcodebuild build-for-testing \
            -scheme "$scheme" \
            -$filetype "$file" \
            -destination "platform=iOS Simulator,name=$DEVICE_NAME,OS=$DEVICE_OS"

      - name: Run Tests
        run: |
          scheme=$(cat default_scheme.txt)
          if ls -A | grep -iq \.xcworkspace$; then
            filetype="workspace"
            file=$(ls -A | grep -i \.xcworkspace$)
          else
            filetype="project"
            file=$(ls -A | grep -i \.xcodeproj$)
          fi

          xcodebuild test-without-building \
            -scheme "$scheme" \
            -$filetype "$file" \
            -destination "platform=iOS Simulator,name=$DEVICE_NAME,OS=$DEVICE_OS"
